### ISSUE TITLE
Accelerate the evaluation process.

### ISSUE THREAD

**Issue by richard-tang199** [Raminghorbanii/PATE#1]
Thanks you for sharing the novel evaluation method. However, the PATE evaluation process is extremely slow. It takes about 130 seconds to evaluate a test dataset with 20,000 points using a Intel 11th i9 CPU. This hinders the application of the method in practice. Is there a way to speed up the evaluation process?

**Comment by Raminghorbanii** [comment]
> Thanks you for sharing the novel evaluation method. However, the PATE evaluation process is extremely slow. It takes about 130 seconds to evaluate a test dataset with 20,000 points using a Intel 11th i9 CPU. This hinders the application of the method in practice. Is there a way to speed up the evaluation process?


Hi @richard-tang199,

Thank you for your feedback and for showing interest in our method. I appreciate your comments as it help us improve PATE and address potential issues.

It is true that PATE's computation speed might be slower due to the complexity of proximity-based weighting and other assessments it performs compared to simpler methods like AUC-PR. This is also true for other complex metrics such as VUS, which often require HPC resources. However, in our tests, PATE was significantly faster than VUS. 

Note that PATE's speed is influenced by the number of anomaly and prediction events rather than the number of data points. Hence, a higher number of events increases the computational load. Could you provide the anomaly event ratio in your dataset? Additionally, if the anomaly detector's scores are unstable, then after thresholding, it might generate many events, thus increasing the computational time (so, anomaly detector performance can influence the speed, better performance of the model gives better speed). Given the complexity and the number of computations involved, if there are a significant number of anomaly events, then 130 seconds with your resources can be considered reasonable!

To help me understand the issue better, could you please try the following suggestions and let me know if they help?

- Parallel Computation: The best way is to consider the parallel setting. Have you tried parallel computation? You can use PATE with parallel processing by setting ```PATE(n_jobs=-1)```.

- Default Settings: Are you using the default settings, or have you modified them?

Buffer Zones: Are you using one combination of buffer zones or multiple? Using ```PATE(num_splits_MaxBuffer=1, include_zero=TRUE)``` can reduce the number of splits in buffer zones, which decreases computation. By setting ```include_zero=FALSE``` you can stop having zero buffer size in the computations which indeed increases the speed as well. 

Number of Thresholds: Consider decreasing the number of thresholds for your anomaly detector score using ```PATE(num_desired_thresholds=250)```. 

- High-Performance Computing: Using HPC with more CPUs and parallel settings is always a choice for increasing speed significantly. Do you have access to such resources? Have you tried using more powerful resources?

I would appreciate your feedback. Let me know if these suggestions help or if you have further questions. I'm willing to help and improve the method for potential issues.
